### ISSUE TITLE
Jsx support?

### ISSUE THREAD

**Issue by greg-murray-volusion** [wallabyjs/wallaby-jest-sample#4]
How does one support Jsx with Wallaby & Jest?  It would be good if the sample included an actual React component in place of the sum function.
Thanks

**Comment by ArtemGovorov** [comment]
You need to add a line to [configure babel](https://wallabyjs.com/docs/integration/es-next.html) to your wallaby config. Here's the [sample repo](https://github.com/wallabyjs/wallaby-jest-snapshots) testing JSX component with [babel configured](https://github.com/wallabyjs/wallaby-jest-snapshots/blob/master/wallaby.js#L17).
