### ISSUE TITLE
Error [Error] Automatic Jest configuration error: Cannot find compatible jest-cli module.

### ISSUE THREAD

**Issue by smarigowda** [wallabyjs/wallaby-jest-sample#5]
When I try to run this sample project, I get the following errors.

[Error] Automatic Jest configuration error: Cannot find compatible jest-cli module.
--
[Info]  2020-02-16T06:34:12.001Z project Wallaby Node version: v10.14.2
[Info]  2020-02-16T06:34:12.002Z project Wallaby config: /Users/santosh/SAN/github/wallaby-jest-snapshots/wallaby.js
[Info]  Started Wallaby.js Core v1.0.781
[Info]  2020-02-16T06:34:12.536Z project File cache: /Users/santosh/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.173/projects/6e10d1a4e1cf231e
[Info]  2020-02-16T06:34:12.546Z uiService Listening port 51235
[Info]  2020-02-16T06:34:12.551Z workers Parallelism for initial run: 10, for regular run: 5
[Info]  2020-02-16T06:34:12.551Z workers Starting run worker instance #0
[Info]  2020-02-16T06:34:12.552Z workers Starting run worker instance #1
[Info]  2020-02-16T06:34:12.552Z workers Starting run worker instance #2
[Info]  2020-02-16T06:34:12.552Z workers Starting run worker instance #3
[Info]  2020-02-16T06:34:12.552Z workers Starting run worker instance #4
[Info]  2020-02-16T06:34:12.552Z workers Starting run worker instance #5
[Info]  2020-02-16T06:34:12.552Z workers Starting run worker instance #6
[Info]  2020-02-16T06:34:12.552Z workers Starting run worker instance #7
[Info]  2020-02-16T06:34:12.552Z workers Starting run worker instance #8
[Info]  2020-02-16T06:34:12.552Z workers Starting run worker instance #9
[Info]  2020-02-16T06:34:12.553Z workers Web server is listening at 50116
[Info]  2020-02-16T06:34:12.585Z project Stopping process pool
[Info]  2020-02-16T06:34:12.585Z project File cache is up-to-date, starting full test run
[Info]  2020-02-16T06:34:12.587Z project Running postprocessor
[Info]  2020-02-16T06:34:12.590Z postprocessor New TypeScript language service is required
[Info]  2020-02-16T06:34:12.591Z postprocessor TypeScript postprocessor will be removed because in 4 project files none were found by patterns: **/*.ts?(x)
[Info]  2020-02-16T06:34:12.592Z project Postprocessor execution finished
[Info]  2020-02-16T06:34:12.592Z project Postprocessor is removed as requested by itself
[Info]  2020-02-16T06:34:12.592Z project Test run started; run priority: 3
[Info]  2020-02-16T06:34:12.592Z project Running all tests
[Info]  2020-02-16T06:34:12.594Z workers Starting test run, priority: 3
[Info]  2020-02-16T06:34:12.594Z nodeRunner Starting sandbox [worker #0, session #mz0c0]
[Info]  2020-02-16T06:34:12.594Z nodeRunner Preparing sandbox [worker #0, session #mz0c0]
[Info]  2020-02-16T06:34:12.898Z workers Started run worker instance (delayed) #0
[Info]  2020-02-16T06:34:12.899Z nodeRunner Prepared sandbox [worker #0, session #mz0c0]
[Info]  2020-02-16T06:34:12.899Z workers [worker #0, session #mz0c0] Running tests in sandbox
[Info]  2020-02-16T06:34:12.905Z workers Started run worker instance (delayed) #3
[Info]  2020-02-16T06:34:12.906Z workers Started run worker instance (delayed) #1
[Info]  2020-02-16T06:34:12.914Z workers Started run worker instance (delayed) #4
[Info]  2020-02-16T06:34:12.914Z workers Started run worker instance (delayed) #2
[Info]  2020-02-16T06:34:12.925Z workers Started run worker instance (delayed) #5
[Info]  2020-02-16T06:34:12.928Z workers Started run worker instance (delayed) #6
[Info]  2020-02-16T06:34:12.932Z workers Started run worker instance (delayed) #7
[Info]  2020-02-16T06:34:12.934Z workers Started run worker instance (delayed) #9
[Info]  2020-02-16T06:34:12.938Z workers Started run worker instance (delayed) #8
[Info]  console.warn: Possibly incompatible Jest version (inline_snapshots)
[Info]  console.error: Error while trying to initialize jest: _path is not defined

**Comment by ArtemGovorov** [comment]
> [Info]  Started Wallaby.js Core v1.0.781

Your current Wallaby Core version was released before we have added support for Jest 25. It means that your license had expired few months ago. If you'd like to keep using the latest version of Wallaby and receive updates, you may consider [updating your Wallaby license](https://wallabyjs.com/purchase/#upgrade) with discount.

**Comment by smarigowda** [comment]
My VS Code was using old license key. License key updated.

 [Info]  Started Wallaby.js Core v1.0.844

It works now. Thanks Artem for quick reply.

[Info]  2020-02-16T06:56:22.182Z project Wallaby Node version: v10.14.2
[Info]  2020-02-16T06:56:22.183Z project Wallaby config: /Users/santosh/SAN/github/wallaby-jest-snapshots/wallaby.js
[Info]  Started Wallaby.js Core v1.0.844
[Info]  2020-02-16T06:56:22.773Z project File cache: /Users/santosh/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.173/projects/6e10d1a4e1cf231e
[Info]  2020-02-16T06:56:22.784Z uiService Listening port 51235
[Info]  2020-02-16T06:56:22.787Z project Config file change detected, invalidating local cache
[Info]  Wallaby App (realtime reports) is available at: http://localhost:51245
[Info]  2020-02-16T06:56:22.793Z workers Parallelism for initial run: 10, for regular run: 5
[Info]  2020-02-16T06:56:22.794Z workers Starting run worker instance #0
[Info]  2020-02-16T06:56:22.794Z workers Starting run worker instance #1
[Info]  2020-02-16T06:56:22.794Z workers Starting run worker instance #2
[Info]  2020-02-16T06:56:22.794Z workers Starting run worker instance #3
[Info]  2020-02-16T06:56:22.794Z workers Starting run worker instance #4
[Info]  2020-02-16T06:56:22.794Z workers Starting run worker instance #5
[Info]  2020-02-16T06:56:22.794Z workers Starting run worker instance #6
[Info]  2020-02-16T06:56:22.794Z workers Starting run worker instance #7
[Info]  2020-02-16T06:56:22.794Z workers Starting run worker instance #8
[Info]  2020-02-16T06:56:22.794Z workers Starting run worker instance #9
[Info]  2020-02-16T06:56:22.795Z workers Web server is listening at 52244
[Info]  2020-02-16T06:56:22.795Z project File cache requires some updates, waiting required files from IDE
[Info]  2020-02-16T06:56:23.509Z workers Started run worker instance (delayed) #2
[Info]  2020-02-16T06:56:23.510Z workers Started run worker instance (delayed) #0
[Info]  2020-02-16T06:56:23.513Z workers Started run worker instance (delayed) #1
[Info]  2020-02-16T06:56:23.514Z workers Started run worker instance (delayed) #4
[Info]  2020-02-16T06:56:23.519Z workers Started run worker instance (delayed) #3
[Info]  2020-02-16T06:56:23.523Z workers Started run worker instance (delayed) #5
[Info]  2020-02-16T06:56:23.524Z workers Started run worker instance (delayed) #6
[Info]  2020-02-16T06:56:23.528Z workers Started run worker instance (delayed) #7
[Info]  2020-02-16T06:56:23.532Z workers Started run worker instance (delayed) #8
[Info]  2020-02-16T06:56:23.537Z workers Started run worker instance (delayed) #9
[Info]  2020-02-16T06:56:24.591Z project Stopping process pool
[Info]  2020-02-16T06:56:24.600Z project Running postprocessor
[Info]  2020-02-16T06:56:24.604Z postprocessor New TypeScript language service is required
[Info]  2020-02-16T06:56:24.604Z postprocessor TypeScript postprocessor will be removed because in 4 project files none were found by patterns: **/*.ts?(x)
[Info]  2020-02-16T06:56:24.605Z project Postprocessor execution finished
[Info]  2020-02-16T06:56:24.605Z project Postprocessor is removed as requested by itself
[Info]  2020-02-16T06:56:24.605Z project Test run started; run priority: 3
[Info]  2020-02-16T06:56:24.606Z project Running all tests
[Info]  2020-02-16T06:56:24.607Z workers Starting test run, priority: 3
[Info]  2020-02-16T06:56:24.607Z nodeRunner Starting sandbox [worker #0, session #yaut4]
[Info]  2020-02-16T06:56:24.607Z nodeRunner Preparing sandbox [worker #0, session #yaut4]
[Info]  2020-02-16T06:56:24.608Z nodeRunner Prepared sandbox [worker #0, session #yaut4]
[Info]  2020-02-16T06:56:24.608Z workers [worker #0, session #yaut4] Running tests in sandbox
[Info]  2020-02-16T06:56:26.209Z workers [yaut4] Loaded unknown number of test(s)
[Info]  2020-02-16T06:56:26.210Z workers [yaut4] Test executed: should be rendered correctly
[Info]  2020-02-16T06:56:26.210Z workers [yaut4] Test executed: should be rendered correctly with different props
[Info]  console.log: PASS src/__tests__/component.spec.js
[Info]  2020-02-16T06:56:26.211Z workers [yaut4] Run 2 test(s), skipped 0 test(s)
[Info]  2020-02-16T06:56:26.212Z workers [yaut4] Sandbox is responsive, closing it
[Info]  Finished executing 2 affected test(s) in 1.61 second(s)
[Info]  2020-02-16T06:56:26.213Z project Test run finished
[Info]  2020-02-16T06:56:26.214Z project Processed console.log entries
[Info]  2020-02-16T06:56:26.214Z project Processed loading sequences
[Info]  2020-02-16T06:56:26.214Z project Processed executed tests
[Info]  2020-02-16T06:56:26.215Z project Processed code coverage
[Info]  2020-02-16T06:56:26.220Z project Test run result processed and sent to IDE
